### ISSUE TITLE
Using 3D ccf coordinates to locate points on the brain

### ISSUE THREAD

**Issue by m2kulkarni** [Yaoyao-Hao/BrainMesh#1]
Hi, i am getting errors while opening nx3 .mat files. I have a ccf file containing 3D coordinates of 698 points. I use scipy.io.savemat to save the datafile. Maybe that is causing the problem. 
Also could you direct me to the code that processes structure tree from points. 

Thanks

```Reference to non-existent field 'ccf'.

Error in BrainMesh/LoadyourpointsButtonPushed (line 476)
                if size(eval(['pts.' file(1:end-4)]),2)~=3
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 335)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by Yaoyao-Hao** [comment]
Hi, sorry for the delay. Make sure your mat file is a n-by-3 matrix. load it into Matlab workspace to assert that. There should be no structure tree in the points. If not working, send me the mat file. let me know. Thanks.
